//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Status
    {
        public long Approve_Id { get; set; }
        public Nullable<long> Applicant_Id { get; set; }
        public string Approving_Admin_id { get; set; }
        public string Application_Status1 { get; set; }
    
        public virtual Applicant_details Applicant_details { get; set; }
    }
}
