//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applicant_details()
        {
            this.Application_Status = new HashSet<Application_Status>();
        }
    
        public long Applicant_Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> Age { get; set; }
        public string Gender { get; set; }
        public string Mobile { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string state { get; set; }
        public string City { get; set; }
        public Nullable<long> Pin { get; set; }
        public Nullable<long> Car_Id { get; set; }
    
        public virtual Vehicle_details Vehicle_details { get; set; }
        public virtual UserLogin_details UserLogin_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_Status> Application_Status { get; set; }
        public virtual Loan_details Loan_details { get; set; }
    }
}
