//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class identity_details
    {
        public string email { get; set; }
        public string Aadhaar { get; set; }
        public string Pan { get; set; }
        public string Profile_pic { get; set; }
        public string Six_months_sal_slip { get; set; }
    
        public virtual UserLogin_details UserLogin_details { get; set; }
    }
}
