//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication15.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PrjGladEntities : DbContext
    {
        public PrjGladEntities()
            : base("name=PrjGladEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applicant_details> Applicant_details { get; set; }
        public virtual DbSet<Application_Status> Application_Status { get; set; }
        public virtual DbSet<Employment_details> Employment_details { get; set; }
        public virtual DbSet<identity_details> identity_details { get; set; }
        public virtual DbSet<Loan_details> Loan_details { get; set; }
        public virtual DbSet<Loan_schemes> Loan_schemes { get; set; }
        public virtual DbSet<UserLogin_details> UserLogin_details { get; set; }
        public virtual DbSet<Vehicle_details> Vehicle_details { get; set; }
    
        public virtual int sp_insert_applicant_details(string name, Nullable<long> age, string gender, string mobile, string email, string address, string state, string city, Nullable<long> pin, Nullable<long> car_Id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(long));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var pinParameter = pin.HasValue ?
                new ObjectParameter("Pin", pin) :
                new ObjectParameter("Pin", typeof(long));
    
            var car_IdParameter = car_Id.HasValue ?
                new ObjectParameter("Car_Id", car_Id) :
                new ObjectParameter("Car_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_applicant_details", nameParameter, ageParameter, genderParameter, mobileParameter, emailParameter, addressParameter, stateParameter, cityParameter, pinParameter, car_IdParameter);
        }
    
        public virtual int sp_insert_employment_details(string email, string type_of_emp, Nullable<decimal> annual_sal, Nullable<decimal> existing_emi)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var type_of_empParameter = type_of_emp != null ?
                new ObjectParameter("Type_of_emp", type_of_emp) :
                new ObjectParameter("Type_of_emp", typeof(string));
    
            var annual_salParameter = annual_sal.HasValue ?
                new ObjectParameter("Annual_sal", annual_sal) :
                new ObjectParameter("Annual_sal", typeof(decimal));
    
            var existing_emiParameter = existing_emi.HasValue ?
                new ObjectParameter("Existing_emi", existing_emi) :
                new ObjectParameter("Existing_emi", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_employment_details", emailParameter, type_of_empParameter, annual_salParameter, existing_emiParameter);
        }
    
        public virtual int sp_insert_identity_details(string email, string aadhaar, string pan, string profile_pic, string six_months_sal_slip)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var aadhaarParameter = aadhaar != null ?
                new ObjectParameter("Aadhaar", aadhaar) :
                new ObjectParameter("Aadhaar", typeof(string));
    
            var panParameter = pan != null ?
                new ObjectParameter("Pan", pan) :
                new ObjectParameter("Pan", typeof(string));
    
            var profile_picParameter = profile_pic != null ?
                new ObjectParameter("Profile_pic", profile_pic) :
                new ObjectParameter("Profile_pic", typeof(string));
    
            var six_months_sal_slipParameter = six_months_sal_slip != null ?
                new ObjectParameter("Six_months_sal_slip", six_months_sal_slip) :
                new ObjectParameter("Six_months_sal_slip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_identity_details", emailParameter, aadhaarParameter, panParameter, profile_picParameter, six_months_sal_slipParameter);
        }
    
        public virtual ObjectResult<sp_show_applicant_details_Result> sp_show_applicant_details(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_show_applicant_details_Result>("sp_show_applicant_details", emailParameter);
        }
    
        public virtual ObjectResult<sp_show_employment_details_Result> sp_show_employment_details(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_show_employment_details_Result>("sp_show_employment_details", emailParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> sp_user_login_details(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("sp_user_login_details", emailParameter, passwordParameter);
        }
    }
}
