//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication15.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [Serializable]
    public partial class UserLogin_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserLogin_details()
        {
            this.Applicant_details = new HashSet<Applicant_details>();
        }
    
        [JsonProperty]
        public string email { get; set; }
        [JsonProperty]
        public string password { get; set; }
        [JsonProperty]
        public string isAdmin { get; set; }
        [JsonProperty]
        public string Admin_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applicant_details> Applicant_details { get; set; }
        public virtual Employment_details Employment_details { get; set; }
        public virtual identity_details identity_details { get; set; }
    }
}
